// Product catalog — the source of truth for what's in the shop.
// `photo` points at a file in public/products, so images ship with the site
// instead of living in browser storage.
//
// Prices and stock counts come from Indiana. Update them here, or from the
// Manage page for quick stock changes.

export const CATALOG = [
  // Turtles
  { id: "turtle-watermelon", name: "Watermelon Turtle", price: 20, blurb: "Big cuddly turtle with a watermelon shell.", photo: "/products/turtles-watermelon-012.jpg", bg: "#DCEEDB", stock: 1, photos: ["/products/turtles-watermelon-012.jpg", "/products/turtles-watermelon-013.jpg", "/products/turtles-watermelon-014.jpg", "/products/turtles-watermelon-015.jpg", "/products/turtles-watermelon-016.jpg"], story: "A big squishy sea turtle with a watermelon shell \u2014 deep red middle, green rind rim, and little seed flecks stitched right in. Four soft flippers and a face that looks permanently pleased with itself." },
  { id: "turtle-dragonfruit", name: "Dragon Fruit Turtle", price: 20, blurb: "Coral shell with speckled dragon fruit flesh.", photo: "/products/turtles-dragon-fruit-003.jpg", bg: "#FBD8E0", stock: 1, photos: ["/products/turtles-dragon-fruit-003.jpg", "/products/turtles-dragon-fruit-001.jpg", "/products/turtles-dragon-fruit-002.jpg", "/products/turtles-dragon-fruit-004.jpg", "/products/turtles-dragon-fruit-005.jpg", "/products/turtles-dragon-fruit-006.jpg"], story: "Coral-pink rind on the outside, creamy speckled dragon fruit on the inside. Easily the most tropical critter in the corner, and very good at sprawling across a shelf." },
  { id: "turtle-strawberry", name: "Strawberry Turtle", price: 20, blurb: "Soft pink shell with a little green top.", photo: "/products/turtles-strawberry-017.jpg", bg: "#FBD8E0", stock: 1, photos: ["/products/turtles-strawberry-017.jpg", "/products/turtles-strawberry-018.jpg", "/products/turtles-strawberry-019.jpg", "/products/turtles-strawberry-020.jpg", "/products/turtles-strawberry-021.jpg"], story: "A dusty-pink strawberry shell with a little green leafy top. Sweet, round, and just the right size to sit in your hands." },
  { id: "turtle-blueberry", name: "Blueberry Turtle", price: 20, blurb: "Sage green shell with a berry crown.", photo: "/products/turtles-blueberry-007.jpg", bg: "#DCEEDB", stock: 1, photos: ["/products/turtles-blueberry-007.jpg", "/products/turtles-blueberry-008.jpg", "/products/turtles-blueberry-009.jpg", "/products/turtles-blueberry-010.jpg", "/products/turtles-blueberry-011.jpg"], story: "Sage green shell with a tiny berry crown on top and soft cream flippers. The calmest turtle of the bunch." },

  // Bees
  { id: "bee-yellow", name: "Bee - Yellow", price: 14, blurb: "Classic black and yellow bumble bee.", photo: "/products/bee-yellow-022.jpg", bg: "#FFE9B3", stock: 4, photos: ["/products/bee-yellow-022.jpg", "/products/bee-yellow-023.jpg", "/products/bee-yellow-024.jpg", "/products/bee-yellow-025.jpg", "/products/bee-yellow-026.jpg"], story: "The classic bumble: fat yellow and black stripes, fluffy white wings, and a face that means no harm to anybody. Fits perfectly in a cupped palm." },
  { id: "bee-pink", name: "Bee - Pink", price: 14, blurb: "Soft pink and black stripes.", photo: "/products/bee-pink-027.jpg", bg: "#FBD8E0", stock: 2, photos: ["/products/bee-pink-027.jpg", "/products/bee-pink-028.jpg", "/products/bee-pink-029.jpg", "/products/bee-pink-030.jpg", "/products/bee-pink-031.jpg"], story: "Same round little bumble, but in soft pink and black. A bee for people who like their bees pastel." },
  { id: "bee-blue", name: "Bee - Blue", price: 14, blurb: "Mint blue stripes with fluffy wings.", photo: "/products/bee-blue-032.jpg", bg: "#DCEEDB", stock: 2, photos: ["/products/bee-blue-032.jpg", "/products/bee-blue-033.jpg", "/products/bee-blue-034.jpg", "/products/bee-blue-035.jpg", "/products/bee-blue-036.jpg"], story: "A minty blue bumble with black stripes and fluffy wings. Not a real bee colour, and much better for it." },

  // Octopus
  { id: "octopus-brown", name: "Octopus - Brown", price: 7, blurb: "Tiny curled-up octopus.", photo: "/products/octopus-brown-082.jpg", bg: "#E8D9BF", stock: 2, photos: ["/products/octopus-brown-082.jpg", "/products/octopus-brown-083.jpg", "/products/octopus-brown-084.jpg", "/products/octopus-brown-085.jpg", "/products/octopus-brown-086.jpg"], story: "A tiny golden-brown octopus with eight curly legs and two dot eyes. Small enough for a pocket, a desk, or a windowsill." },
  { id: "octopus-teal", name: "Octopus - Teal", price: 7, blurb: "Bright mint tentacles.", photo: "/products/octopus-teal-087.jpg", bg: "#DCEEDB", stock: 2, photos: ["/products/octopus-teal-087.jpg", "/products/octopus-teal-088.jpg", "/products/octopus-teal-089.jpg", "/products/octopus-teal-090.jpg", "/products/octopus-teal-091.jpg", "/products/octopus-teal-092.jpg"], story: "Bright mint tentacles and a round little head. Curls up neatly in your hand." },
  { id: "octopus-pink", name: "Octopus - Pink", price: 7, blurb: "Dusty pink little friend.", photo: "/products/octopus-pink-093.jpg", bg: "#FBD8E0", stock: 2, photos: ["/products/octopus-pink-093.jpg", "/products/octopus-pink-094.jpg", "/products/octopus-pink-095.jpg", "/products/octopus-pink-096.jpg", "/products/octopus-pink-097.jpg"], story: "A soft dusty-pink octopus with eight squiggly legs. Very small, very pleased to be here." },
  { id: "octopus-blue", name: "Octopus - Blue", price: 7, blurb: "Soft sage blue octopus.", photo: "/products/octopus-blue-098.jpg", bg: "#DCEEDB", stock: 2, photos: ["/products/octopus-blue-098.jpg", "/products/octopus-blue-099.jpg", "/products/octopus-blue-100.jpg", "/products/octopus-blue-101.jpg", "/products/octopus-blue-102.jpg"], story: "A gentle sage-blue octopus with curly legs and a round head. Quiet company for a desk." },
  { id: "octopus-leopard", name: "Octopus - Leopard", price: 7, blurb: "Speckled leopard print octopus.", photo: "/products/octopus-leopard-077.jpg", bg: "#EDEDE6", stock: 2, photos: ["/products/octopus-leopard-077.jpg", "/products/octopus-leopard-076.jpg", "/products/octopus-leopard-078.jpg", "/products/octopus-leopard-079.jpg", "/products/octopus-leopard-080.jpg", "/products/octopus-leopard-081.jpg"], story: "Speckled black-and-cream yarn makes this one look like a tiny leopard octopus. No two come out with the same spots." },

  // Chickens
  { id: "chicken-white", name: "Chicken - White", price: 12, blurb: "Little white hen with a red comb.", photo: "/products/chickens-white-106.jpg", bg: "#FFFDF7", stock: 2, photos: ["/products/chickens-white-106.jpg", "/products/chickens-white-103.jpg", "/products/chickens-white-104.jpg", "/products/chickens-white-105.jpg", "/products/chickens-white-107.jpg"], story: "A plump little white hen with a deep red comb and a tail that sticks up. Sits flat and looks smug about it." },
  { id: "chicken-brown", name: "Chicken - Brown", price: 12, blurb: "Warm golden brown hen.", photo: "/products/chickens-brown-113.jpg", bg: "#E8D9BF", stock: 2, photos: ["/products/chickens-brown-113.jpg", "/products/chickens-brown-114.jpg", "/products/chickens-brown-115.jpg", "/products/chickens-brown-116.jpg", "/products/chickens-brown-117.jpg"], story: "A warm golden hen with a red comb and a soft cream beak. Round, heavy-feeling, and extremely sit-able." },
  { id: "chicken-leopard", name: "Chicken - Leopard", price: 12, blurb: "Speckled hen with a red comb.", photo: "/products/chickens-leopard-109.jpg", bg: "#EDEDE6", stock: 2, photos: ["/products/chickens-leopard-109.jpg", "/products/chickens-leopard-108.jpg", "/products/chickens-leopard-110.jpg", "/products/chickens-leopard-111.jpg", "/products/chickens-leopard-112.jpg"], story: "Speckled black-and-white yarn gives this hen a proper freckled look. Red comb, tiny beak, big presence." },

  // Loaf cats
  { id: "loafcat-white", name: "Loaf Cat - White", price: 14, blurb: "A cat, loafing.", photo: "/products/loaf-cats-white-042.jpg", bg: "#FFFDF7", stock: 2, photos: ["/products/loaf-cats-white-042.jpg", "/products/loaf-cats-white-043.jpg", "/products/loaf-cats-white-044.jpg", "/products/loaf-cats-white-045.jpg", "/products/loaf-cats-white-046.jpg", "/products/loaf-cats-white-047.jpg"], story: "A cat that has fully committed to being a loaf. Cream white, round on all sides, with a long tail and a sleepy little face." },
  { id: "loafcat-leopard", name: "Loaf Cat - Leopard Print", price: 14, blurb: "Speckled loaf with a long tail.", photo: "/products/loaf-cats-leopard-print-038.jpg", bg: "#EDEDE6", stock: 2, photos: ["/products/loaf-cats-leopard-print-038.jpg", "/products/loaf-cats-leopard-print-037.jpg", "/products/loaf-cats-leopard-print-039.jpg", "/products/loaf-cats-leopard-print-040.jpg", "/products/loaf-cats-leopard-print-041.jpg"], story: "The same happy loaf, in speckled leopard yarn. Long tail, tiny ears, absolutely no intention of moving." },

  // Axolotls
  { id: "axolotl-pink", name: "Axolotl - Pink", price: 8, blurb: "Pink axolotl with mint frills.", photo: "/products/axolotol-pink-055.jpg", bg: "#FBD8E0", stock: 2, photos: ["/products/axolotol-pink-055.jpg", "/products/axolotol-pink-053.jpg", "/products/axolotol-pink-054.jpg", "/products/axolotol-pink-056.jpg", "/products/axolotol-pink-057.jpg"], story: "A pink axolotl with mint frilly gills and a permanent smile. Small, floppy, and very good at lying flat." },
  { id: "axolotl-teal", name: "Axolotl - Teal", price: 8, blurb: "Mint axolotl with pink frills.", photo: "/products/axolotol-teal-051.jpg", bg: "#DCEEDB", stock: 2, photos: ["/products/axolotol-teal-051.jpg", "/products/axolotol-teal-048.jpg", "/products/axolotol-teal-049.jpg", "/products/axolotol-teal-050.jpg", "/products/axolotol-teal-052.jpg"], story: "Mint green with pink frills. The other half of the axolotl pair, if you can't choose just one." },

  // Leggy frogs
  { id: "frog-light-green", name: "Leggy Frog - Light Green", price: 7, blurb: "Bright green frog with long legs.", photo: "/products/leggy-frog-light-green-149.jpg", bg: "#DCEEDB", stock: 4, photos: ["/products/leggy-frog-light-green-149.jpg", "/products/leggy-frog-light-green-147.jpg", "/products/leggy-frog-light-green-148.jpg", "/products/leggy-frog-light-green-150.jpg", "/products/leggy-frog-light-green-151.jpg"], story: "Bright green with long dangly legs that flop over anything you drape him on. Shelves, monitors, your arm." },
  { id: "frog-dark-green", name: "Leggy Frog - Dark Green", price: 7, blurb: "Sage green frog with long legs.", photo: "/products/leggy-frog-dark-green--152.jpg", bg: "#C3DFC0", stock: 4, photos: ["/products/leggy-frog-dark-green--152.jpg", "/products/leggy-frog-dark-green--153.jpg", "/products/leggy-frog-dark-green--154.jpg", "/products/leggy-frog-dark-green--155.jpg", "/products/leggy-frog-dark-green--156.jpg"], story: "The same long-legged frog in deeper sage green. Legs are the whole point." },

  // Snakes
  { id: "snake-teal", name: "Snake - Teal", price: 5, blurb: "A long mint noodle friend.", photo: "/products/snakes-teal-071.jpg", bg: "#DCEEDB", stock: 2, photos: ["/products/snakes-teal-071.jpg", "/products/snakes-teal-072.jpg", "/products/snakes-teal-073.jpg", "/products/snakes-teal-074.jpg", "/products/snakes-teal-075.jpg"], story: "A long mint noodle with two dot eyes. Curls, coils, drapes \u2014 a genuinely excellent little snake." },

  // Positive potatoes
  { id: "potato-brown", name: "Positive Potato", price: 8, blurb: "A little spud rooting for you.", photo: "/products/positive-potatoes-brown-118.jpg", bg: "#E8D9BF", stock: 3, photos: ["/products/positive-potatoes-brown-118.jpg", "/products/positive-potatoes-brown-119.jpg", "/products/positive-potatoes-brown-120.jpg", "/products/positive-potatoes-brown-121.jpg", "/products/positive-potatoes-brown-122.jpg"], story: "A small brown potato with a face. That's the whole product, and it's rooting for you." },

  // Keychains
  { id: "keychain-strawberry", name: "Strawberry Keychain", price: 5, blurb: "Little strawberry on a keyring.", photo: "/products/strawberry-keychains-pink-062.jpg", bg: "#FBD8E0", stock: 3, photos: ["/products/strawberry-keychains-pink-062.jpg", "/products/strawberry-keychains-pink-060.jpg", "/products/strawberry-keychains-pink-061.jpg", "/products/strawberry-keychains-pink-063.jpg", "/products/strawberry-keychains-pink-064.jpg", "/products/strawberry-keychains-pink-065.jpg", "/products/strawberry-keychains-pink-066.jpg", "/products/strawberry-keychains-pink-067.jpg", "/products/strawberry-keychains-pink-068.jpg", "/products/strawberry-keychains-pink-069.jpg", "/products/strawberry-keychains-pink-070.jpg"], story: "A little pink strawberry with green leaves on a keyring. Small enough not to get in the way, cute enough to notice every time." },
  { id: "keychain-flower-yellow", name: "Flower Keychain - Yellow", price: 5, blurb: "Yellow bloom on a green stem.", photo: "/products/flower-keychains-yellow-127.jpg", bg: "#FFE9B3", stock: 3, photos: ["/products/flower-keychains-yellow-127.jpg", "/products/flower-keychains-yellow-123.jpg", "/products/flower-keychains-yellow-124.jpg", "/products/flower-keychains-yellow-125.jpg", "/products/flower-keychains-yellow-126.jpg"], story: "A yellow bloom on a twisty green stem with a keyring at the top. Brightens up a very boring set of keys." },
  { id: "keychain-flower-white", name: "Flower Keychain - White", price: 5, blurb: "White bloom on a green stem.", photo: "/products/flower-keychains-white-128.jpg", bg: "#FFFDF7", stock: 1, photos: ["/products/flower-keychains-white-128.jpg", "/products/flower-keychains-white-129.jpg", "/products/flower-keychains-white-130.jpg", "/products/flower-keychains-white-131.jpg", "/products/flower-keychains-white-132.jpg"], story: "A soft white bloom on a green stem, finished with a keyring. Simple and sweet." },

  // Scrunchies
  { id: "scrunchie-pink", name: "Scrunchie - Pink", price: 5, blurb: "Soft fuzzy hair scrunchie.", photo: "/products/scrunchies-pink-058.jpg", bg: "#FBD8E0", stock: 2, photos: ["/products/scrunchies-pink-058.jpg", "/products/scrunchies-pink-059.jpg"], story: "A soft fuzzy scrunchie in pale pink. Gentle on hair, and much nicer to look at than a plain elastic." },

  // Wallets
  { id: "wallet-green", name: "Wallet - Green", price: 8, blurb: "Sturdy little card wallet.", photo: "/products/wallets-green-141.jpg", bg: "#DCEEDB", stock: 1, photos: ["/products/wallets-green-141.jpg", "/products/wallets-green-142.jpg"], story: "A small hand-crocheted card wallet in bright green. Tight, sturdy stitches \u2014 holds cards and folded notes." },
  { id: "wallet-light-green", name: "Wallet - Light Green", price: 8, blurb: "Sturdy little card wallet.", photo: "/products/wallets-light-green-145.jpg", bg: "#DCEEDB", stock: 1, photos: ["/products/wallets-light-green-145.jpg"], story: "A soft green card wallet, crocheted tight so it keeps its shape. Slim enough for a pocket." },
  { id: "wallet-orange", name: "Wallet - Orange", price: 8, blurb: "Sturdy little card wallet.", photo: "/products/wallets-orange-143.jpg", bg: "#F5D5B8", stock: 1, photos: ["/products/wallets-orange-143.jpg"], story: "A warm orange card wallet with dense, sturdy stitches. Small, flat, and hard to lose in a bag." },
  { id: "wallet-cream", name: "Wallet - Cream", price: 8, blurb: "Sturdy little card wallet.", photo: "/products/wallets-cream-144.jpg", bg: "#F5EFDD", stock: 1, photos: ["/products/wallets-cream-144.jpg"], story: "A natural cream card wallet. Neutral, tidy, and goes with everything." },
  { id: "wallet-red", name: "Wallet - Red", price: 8, blurb: "Sturdy little card wallet.", photo: "/products/wallets-red-146.jpg", bg: "#F2C6BD", stock: 1, photos: ["/products/wallets-red-146.jpg"], story: "A deep red card wallet, crocheted firm so it holds its shape. Cards in, fold over, done." },

  // Bracelets
  { id: "bracelet-yellow", name: "Bracelet - Yellow", price: 3, blurb: "Hand-braided friendship bracelet.", photo: "/products/braclets-yellow-133.jpg", bg: "#FFE9B3", stock: 3, photos: ["/products/braclets-yellow-133.jpg"], story: "A hand-braided bracelet in sunny yellow. Ties on, sits soft against your wrist." },
  { id: "bracelet-yellow-white", name: "Bracelet - Yellow & White", price: 3, blurb: "Hand-braided friendship bracelet.", photo: "/products/braclets-yellow-and-white-134.jpg", bg: "#FFE9B3", stock: 3, photos: ["/products/braclets-yellow-and-white-134.jpg"], story: "Yellow and white braided together into a soft twisted bracelet. Simple and summery." },
  { id: "bracelet-green-yellow", name: "Bracelet - Green & Yellow", price: 3, blurb: "Hand-braided friendship bracelet.", photo: "/products/braclets-green-and-yellow-135.jpg", bg: "#DCEEDB", stock: 3, photos: ["/products/braclets-green-and-yellow-135.jpg", "/products/braclets-green-and-yellow-139.jpg"], story: "Green and yellow twisted together for a friendship bracelet you'd actually keep wearing." },
  { id: "bracelet-green", name: "Bracelet - Green", price: 3, blurb: "Hand-braided friendship bracelet.", photo: "/products/braclets-green-136.jpg", bg: "#DCEEDB", stock: 3, photos: ["/products/braclets-green-136.jpg"], story: "A bright green braided bracelet. One colour, done well." },
  { id: "bracelet-orange", name: "Bracelet - Orange", price: 3, blurb: "Hand-braided friendship bracelet.", photo: "/products/braclets-orange-137.jpg", bg: "#F5D5B8", stock: 3, photos: ["/products/braclets-orange-137.jpg"], story: "A warm orange braided bracelet, soft enough to forget you're wearing it." },
  { id: "bracelet-brown", name: "Bracelet - Brown", price: 3, blurb: "Hand-braided friendship bracelet.", photo: "/products/braclets-brown-138.jpg", bg: "#E8D9BF", stock: 3, photos: ["/products/braclets-brown-138.jpg"], story: "A dark brown braided bracelet. Understated, and goes with anything." },
  { id: "bracelet-brown-white", name: "Bracelet - Brown & White", price: 3, blurb: "Hand-braided friendship bracelet.", photo: "/products/braclets-brown-and-white-140.jpg", bg: "#E8D9BF", stock: 3, photos: ["/products/braclets-brown-and-white-140.jpg"], story: "Brown and cream braided together for a soft two-tone bracelet." },
];

// Bump this when the catalog changes so browsers pick up the new list
// instead of showing whatever was seeded on a previous visit.
export const CATALOG_VERSION = "2026-07-29-details";
